<?php
declare(strict_types=1);

namespace ParkkTech\FastMagento\Plugin;

use Magento\AdvancedSearch\Model\Client\ClientResolver;
use Magento\Framework\App\Config\ScopeConfigInterface;
use Magento\Framework\Search\EngineResolverInterface;
use Magento\Store\Model\ScopeInterface;
use Magento\UrlRewrite\Model\UrlFinderInterface;
use Magento\UrlRewrite\Service\V1\Data\UrlRewrite;
use Magento\UrlRewrite\Service\V1\Data\UrlRewriteFactory;
use ParkkTech\FastMagento\Helper\OpenSearchConfig;
use ParkkTech\FastMagento\Model\OpenSearch\CategoryDataProvider;
use Psr\Log\LoggerInterface;

/**
 * URL rewrites answered from the indexes instead of url_rewrite.
 *
 * Two shapes are served:
 *
 *  1. Routing (request_path + store_id): what the URL-rewrite router asks for every request.
 *     A category request path is looked up in the indexed category tree; a product request
 *     path is one term query on the product index. Either answer is an autogenerated,
 *     non-redirecting rewrite to the entity's view action — exactly what url_rewrite holds for
 *     a current canonical path. Anything the indexes do not know (old paths that 301, CMS
 *     pages, product-in-category paths, custom rewrites) falls through to the database, so
 *     redirects keep working. The router's follow-up lookup of the resolved system path
 *     (catalog/category/view/id/N, catalog/product/view/id/N) is answered "no rewrite" without
 *     a query: a custom rewrite whose REQUEST path is a system path is not a supported shape.
 *
 *  2. entity_type=category + entity_id (+ store): a category's own URL, asked once per
 *     category rendered in menus and breadcrumbs. Served from the tree's request_path; the
 *     previous batch-then-map fallback stays for categories the tree does not have.
 */
class CategoryUrlFinderPlugin
{
    public const XML_PATH_SERVE_URLS = 'fastmagento/serving/serve_url_rewrites';

    private array $categoryMap = [];
    private ?array $pathToCategory = null;
    private ?object $client = null;

    public function __construct(
        private readonly CategoryDataProvider $categoryData,
        private readonly UrlRewriteFactory $urlRewriteFactory,
        private readonly ScopeConfigInterface $scopeConfig,
        private readonly ClientResolver $clientResolver,
        private readonly EngineResolverInterface $engineResolver,
        private readonly OpenSearchConfig $openSearchConfig,
        private readonly LoggerInterface $logger
    ) {
    }

    public function aroundFindOneByData(UrlFinderInterface $subject, callable $proceed, array $data)
    {
        try {
            if (array_key_exists(UrlRewrite::REQUEST_PATH, $data)) {
                $answer = $this->byRequestPath($data);
                if ($answer === false) {
                    return null;
                }
                return $answer ?? $proceed($data);
            }
            if (($data[UrlRewrite::ENTITY_TYPE] ?? null) === 'category'
                && isset($data[UrlRewrite::ENTITY_ID], $data[UrlRewrite::STORE_ID])
                && !is_array($data[UrlRewrite::ENTITY_ID])
            ) {
                return $this->categoryById($subject, $data);
            }
        } catch (\Throwable $e) {
            $this->logger->debug('[FastMagento] url finder from index: ' . $e->getMessage());
        }
        return $proceed($data);
    }

    // ---- routing

    /**
     * @return UrlRewrite|false|null  a rewrite; FALSE = "known to have none" (return null to
     *                                the caller without a query); NULL = cannot answer, use MySQL
     */
    private function byRequestPath(array $data)
    {
        if (!$this->scopeConfig->isSetFlag(self::XML_PATH_SERVE_URLS, ScopeInterface::SCOPE_STORE)
            || !isset($data[UrlRewrite::STORE_ID]) || is_array($data[UrlRewrite::STORE_ID])
            || count($data) !== 2
        ) {
            return null;
        }
        $paths = array_values((array) $data[UrlRewrite::REQUEST_PATH]);
        $path = rtrim((string) ($paths[0] ?? ''), '/');
        if ($path === '') {
            return null;
        }
        if (preg_match('#^catalog/(category|product)/view/id/\d+#', $path)) {
            return false;
        }
        $storeId = (int) $data[UrlRewrite::STORE_ID];

        $categoryId = $this->categoryByPath($path, $storeId);
        if ($categoryId) {
            return $this->rewrite('category', $categoryId, $path, 'catalog/category/view/id/' . $categoryId, $storeId);
        }
        $productId = $this->productByPath($path);
        if ($productId) {
            return $this->rewrite('product', $productId, $path, 'catalog/product/view/id/' . $productId, $storeId);
        }
        return null;
    }

    private function categoryByPath(string $path, int $storeId): int
    {
        if (!$this->categoryData->isAvailable()) {
            return 0;
        }
        if ($this->pathToCategory === null) {
            $this->pathToCategory = [];
            foreach ($this->categoryData->getAll() as $id => $doc) {
                $rp = (string) ($doc['request_path'] ?? '');
                if ($rp !== '' && (int) ($doc['store_id'] ?? $storeId) === $storeId) {
                    $this->pathToCategory[$rp] = (int) $id;
                }
            }
        }
        return $this->pathToCategory[$path] ?? 0;
    }

    private function productByPath(string $path): int
    {
        $client = $this->getClient();
        if (!$client) {
            return 0;
        }
        // request_path is a keyword field only on indexes built since it was mapped; on an
        // older index the term query simply finds nothing and MySQL answers as before.
        $resp = $client->search([
            'index' => $this->openSearchConfig->getIndexName(),
            'body' => [
                'size' => 1,
                '_source' => false,
                'query' => ['term' => ['request_path' => $path]],
            ],
        ]);
        $hit = $resp['hits']['hits'][0]['_id'] ?? null;
        return $hit === null ? 0 : (int) $hit;
    }

    private function rewrite(string $type, int $entityId, string $requestPath, string $targetPath, int $storeId): UrlRewrite
    {
        /** @var UrlRewrite $rewrite */
        $rewrite = $this->urlRewriteFactory->create();
        $rewrite->setEntityType($type)
            ->setEntityId($entityId)
            ->setRequestPath($requestPath)
            ->setTargetPath($targetPath)
            ->setRedirectType(0)
            ->setStoreId($storeId)
            ->setIsAutogenerated(1)
            ->setMetadata(null);
        return $rewrite;
    }

    // ---- category by id

    private function categoryById(UrlFinderInterface $subject, array $data)
    {
        $entityId = (int) $data[UrlRewrite::ENTITY_ID];
        $storeId = (int) $data[UrlRewrite::STORE_ID];
        if ($this->scopeConfig->isSetFlag(self::XML_PATH_SERVE_URLS, ScopeInterface::SCOPE_STORE)
            && $this->categoryData->isAvailable()
            && (int) (($doc = $this->categoryData->getById($entityId))['store_id'] ?? 0) === $storeId
            && ($doc['request_path'] ?? '') !== ''
        ) {
            return $this->rewrite('category', $entityId, (string) $doc['request_path'], 'catalog/category/view/id/' . $entityId, $storeId);
        }
        // Batch-then-map fallback: one findAllByData for all categories in the store, then
        // in-memory lookups, instead of one query per category rendered.
        $batchFilter = $data;
        unset($batchFilter[UrlRewrite::ENTITY_ID]);
        $cacheKey = $this->cacheKey($batchFilter);
        if (!isset($this->categoryMap[$cacheKey])) {
            $map = [];
            foreach ($subject->findAllByData($batchFilter) as $rewrite) {
                $map[(int) $rewrite->getEntityId()] ??= $rewrite;
            }
            $this->categoryMap[$cacheKey] = $map;
        }
        return $this->categoryMap[$cacheKey][$entityId] ?? null;
    }

    private function cacheKey(array $filter): string
    {
        ksort($filter);
        return implode('|', array_map(
            static fn ($k, $v) => $k . '=' . (is_array($v) ? implode(',', $v) : (string) $v),
            array_keys($filter),
            $filter
        ));
    }

    private function getClient(): ?object
    {
        if ($this->client === null) {
            $this->client = $this->clientResolver
                ->create($this->engineResolver->getCurrentSearchEngine())
                ->getOpenSearchClient();
        }
        return $this->client;
    }
}
